### ISSUE TITLE
Update to gostatsd v35.0.0

### ISSUE THREAD

**Issue by msummers-nr** [newrelic/nri-statsd#27] opened 2022-05-13 19:44 UTC
## Is your feature request related to a problem? Please describe.
Yes, we need the new `statsdSource` tag for monitoring HCP Consul clusters

## Feature Description
Update to gostatsd v35.0.0

## Describe Alternatives
There are no alternatives

## Additional context
Required for HCP Consul monitoring

## Priority
Blocker

**Comment by davidgit** [comment] 2022-06-07 15:07
Duplicate of #29

**Closed** 2022-06-14 10:35 UTC
Labels: triage/accepted
